.Dd July 31, 2023
.Dt PAGINATOR 1
.Os
.Sh NAME
.Nm paginator
.Nd X11 desktop pager
.Sh SYNOPSIS
.Nm
.Op Fl geometry Ar geometry
.Op Fl name Ar name
.Op Fl xrm Ar resources
.Ar nrows ncols
.Op Ar primary secondary
.Sh DESCRIPTION
.Nm
is a desktop pager for X11 that provides to the user a graphical interface
to change the current desktop or the current window.
It displays a grid of desktop miniatures
representing actual virtual desktops managed by the window manager;
on each desktop miniature there are window miniatures
representing actual client windows on the screen.
Each window miniature is identified by the icon of the client window
it represents.
The user can change the desktop of a client by drag-and-dropping its
window miniature to another desktop miniature on the pager.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl geometry Ar geometry
Specify the initial size and location of the window.
The format for the
.Ar geometry
argument is specified at
.Xr XParseGeometry 3 .
.It Fl name Ar name
Specify the name of
.Nm
instance used to retrieve resources.
If not specified, defaults to the value of the
.Ev RESOURCES_NAME
environment variable, or (if that variable is not set)
to the basename of the command
.Nm
was invoked as.
.It Fl xrm Ar resources
Specify additional resources to merge on top of X11's resouces database.
If not specified, defaults to the value of the
.Ev RESOURCES_DATA
environment variable, or (if that variable is not set)
to the empty string.
.El
.Pp
The first and second obligatory arguments,
.Ar nrows
and
.Ar ncols
are the number of rows and columns in the desktop grid.
.Pp
The first and second optional arguments,
.Ar primary
and
.Ar secondary ,
must each be set to either
.Cm top ,
.Cm bottom ,
.Cm left ,
or
.Cm right .
These values specify a top-to-bottom, bottom-to-top, left-to-right or right-to-left
primary and secondary placement respectively.
.Pp
.Nm
only works in cooperation with EWMH-compliant window managers which set the
_NET_CLIENT_LIST_STACKING and _NET_NUMBER_OF_DESKTOPS
properties.
.Sh RESOURCES
.Nm
understands the following X resources.
They must be prefixed with either the
.Qq Ic Paginator
class, or the name given with the
.Fl name
command-line option, followed by a period.
.Bl -tag -width Ds
.It Ic activeBackground
The color of the background of the active window.
.It Ic activeBorderColor
The color of the border of the active window.
.It Ic activeTopShadowColor , activeBottomShadowColor
The light and dark colors of the Motif-like 3D shadow of the active window.
.It Ic borderWidth
The width in pixels of the borders of the window miniatures 
.It Ic background
The color of the desktop miniatures.
.It Ic foreground
The color of the desktop miniature for the current desktop.
.It Ic geometry
The initial size and location of Paginator.
.It Ic inactiveBackground
The color of the background of the inactive window.
.It Ic inactiveBorderColor
The color of the border of the inactive window.
.It Ic inactiveTopShadowColoror , inactiveBottomShadowColor
The light and dark colors of the Motif-like 3D shadow of the inactive window.
.It Ic separatorWidth
The width in pixels of the separators between desktop miniatures.
.It Ic shadowThickness
The width in pixels of the Motif-like 3D shadow borders.
.It Ic urgentBackground
The color of the background of the urgent window.
.It Ic urgentBorderColor
The color of the border of the urgent window.
.It Ic urgentTopShadowColoror , urgentBottomShadowColor
The light and dark colors of the Motif-like 3D shadow of the urgent window.
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm
.Bl -tag -width Ds
.It DISPLAY
The display to start
.Nm
on.
.El
.Sh EXAMPLES
To create a pager with 6 virtual desktops distributed as follows...
.Bd -literal -offset indent
+-------+-------+-------+
|       |       |       |
|   6   |   4   |   2   |
|       |       |       |
+-------+-------+-------+
|       |       |       |
|   5   |   3   |   1   |
|       |       |       |
+-------+-------+-------+
.Ed
.Pp
\&...run the following command:
.Bd -literal -offset indent
$ paginator 2 3 bottom right
.Ed
.Pp
The following command creates a pager with a 2x2 grid and default orientation:
.Bd -literal -offset indent
$ paginator 2 2
.Ed
.Sh SEE ALSO
.Xr X 7
