.Dd September 21, 2022
.Dt PAGINATOR 1
.Os
.Sh NAME
.Nm paginator
.Nd X11 desktop pager
.Sh SYNOPSIS
.Nm
.Op Fl iw
.Op Fl c Ar corner
.Op Fl g Ar geometry
.Op Fl l Ar layout
.Op Fl o Ar orientation
.Sh DESCRIPTION
.Nm
is a desktop pager for X11 that provides to the user a graphical interface
to change the current desktop or the current window.
It can also change the desktop of a window by drag-and-dropping it to
another desktop on the pager.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar corner
Specify the corner of the pager in which the first desktop should be placed.
The argument for this option must be
.Cm TL ,
.Cm TR ,
.Cm BL ,
or
.Cm BR
(top-left, top-right, bottom-left, or bottom-right, respectively).
If not provided, the starting corner will be top-left.
.It Fl g Ar geometry
Specify a size for the pager window.
The argument for this option must be a geometry specification recognized by
.Xr XParseGeometry 1
If not provided, the window size will be computed from
the pager layout, the number of desktops and the size of the screen.
.It Fl i
Draw window icons on the pager.
.It Fl l Ar layout
Specify the layout of the pager.
The argument for this option must be in the format
.Ar NCOLSPxNROWS ,
where
.Ar NCOLS
is the number of columns in the pager, and
.Ar NROWS
is the number of rows in the pager.
If not specified, the number of columns will be 2,
and the number of rows will be computed from the number of desktops.
.It Fl o Ar orientation
Specify the orientation of the desktops on the pager.
The argument for this option must be
.Cm H ,
or
.Cm V
(horizontal or vertical, respectively).
If not provided, the starting corner will be horizontal.
.It Fl w
Start in the withdrawn mode.
This makes
.Nm
work like a dockapp.
.El
.Pp
.Nm
only works in cooperation with EWMH-compliant window managers.
In particular, with window managers which set the
_NET_CLIENT_LIST_STACKING and _NET_NUMBER_OF_DESKTOPS
properties.
.Sh RESOURCES
.Nm
understands the following X resources.
.Bl -tag -width Ds
.It Ic "paginator.activeBackground"
The color of the background of the active window.
.It Ic "paginator.activeTopShadowColor"
The color of the top 3D shadow of the active window.
.It Ic "paginator.activeBottomShadowColor"
The color of the bottom 3D shadow of the active window.
.It Ic "paginator.background"
The color of the background of the desktops.
.It Ic "paginator.inactiveBackground"
The color of the background of inactive windows.
.It Ic "paginator.inactiveTopShadowColor"
The color of the top 3D shadow of inactive windows.
.It Ic "paginator.inactiveBottomShadowColor"
The color of the bottom 3D shadow of inactive windows.
.It Ic "paginator.orientation"
The orientation of the desktops on the pager.
Its value must be
.Cm Horizontal
or
.Cm Vertical .
.It Ic "paginator.numColumns"
The number of columns in the pager.
.It Ic "paginator.numRows"
The number of rows in the pager.
.It Ic "paginator.shadowThickness"
Thickness of the 3D shadow effect, in pixels.
.It Ic "paginator.selbackground"
The color of the background of the active desktop.
.It Ic "paginator.separator"
The color of the separator between desktops.
.It Ic "paginator.startingCorner"
Specify the corner of the pager in which the first desktop should be placed.
The argument for this option must be
.Cm TopLeft ,
.Cm TopRight ,
.Cm BotomLeft ,
or
.Cm BotomRight .
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm
.Bl -tag -width Ds
.It DISPLAY
The display to start
.Nm
on.
.El
.Sh SEE ALSO
.Xr taskinator 1 ,
.Xr X 1
